<?php

namespace Sistema\GuiasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Categoria_x_GuiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaGuiaRepository extends EntityRepository
{
}
