entityName: 'Categoria'
entity: 'Sistema\GuiasBundle\Entity\Categoria'
repository: 'SistemaGuiasBundle:Categoria'
index: 'admin_categoria'
new: 'admin_categoria_new'
edit: 'admin_categoria_edit'
show: 'admin_categoria_show'
create: 'admin_categoria_create'
update: 'admin_categoria_update'
delete: 'admin_categoria_delete'
sessionFilter: 'CategoriaControllerFilter'
fieldsindex:    
#    a.id:
#        label: 'Id'
#        name: 'Id'
#        type: 'integer'    
    a.nombre:
        label: 'Nombre'
        name: 'Nombre'
        type: 'string'    
    a.codigo:
        label: 'Codigo'
        name: 'Codigo'
        type: 'string'
fieldsshow:
#    a.id:
#        label: 'Id'
#        name: 'Id'
#        type: 'integer'
    a.nombre:
        label: 'Nombre'
        name: 'Nombre'
        type: 'string'
    a.codigo:
        label: 'Codigo'
        name: 'Codigo'
        type: 'string'
#    a.categoriaguias:
#        label: 'Categoriaguias'
#        name: 'Categoriaguias'
#        type: 'ONE_TO_MANY'