entityName: 'Finalidad'
entity: 'Sistema\GuiasBundle\Entity\Finalidad'
repository: 'SistemaGuiasBundle:Finalidad'
index: 'admin_finalidad'
new: 'admin_finalidad_new'
edit: 'admin_finalidad_edit'
show: 'admin_finalidad_show'
create: 'admin_finalidad_create'
update: 'admin_finalidad_update'
delete: 'admin_finalidad_delete'
sessionFilter: 'FinalidadControllerFilter'
fieldsindex:    
#    a.id:
#        label: 'Id'
#        name: 'Id'
#        type: 'integer'    
    a.nombre:
        label: 'Nombre'
        name: 'Nombre'
        type: 'string'
fieldsshow:
#    a.id:
#        label: 'Id'
#        name: 'Id'
#        type: 'integer'
    a.nombre:
        label: 'Nombre'
        name: 'Nombre'
        type: 'string'
#    a.guias:
#        label: 'Guias'
#        name: 'Guias'
#        type: 'ONE_TO_MANY'